CREATE TABLE customer (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      name VARCHAR(100) NOT NULL,
      contact_email VARCHAR(150) NOT NULL,

      created_at TIMESTAMP NOT NULL,
      created_by BIGINT,

      updated_at TIMESTAMP NOT NULL,
      updated_by BIGINT
);