CREATE TABLE part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    sku VARCHAR(50) UNIQUE,

    unit_cost DECIMAL(10,2),
    stock_qty INTEGER DEFAULT 0,

    created_at TIMESTAMP NOT NULL,
    created_by BIGINT,

    updated_at TIMESTAMP NOT NULL,
    updated_by BIGINT
);