CREATE TABLE part_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    work_order_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,

    qty_used INTEGER NOT NULL,

    created_at TIMESTAMP NOT NULL,
    created_by BIGINT,

    updated_at TIMESTAMP NOT NULL,
    updated_by BIGINT,

    CONSTRAINT fk_partusage_workorder
        FOREIGN KEY(work_order_id)
        REFERENCES work_order(id),

    CONSTRAINT fk_partusage_part
        FOREIGN KEY(part_id)
        REFERENCES part(id)
);