CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),

    created_at TIMESTAMP NOT NULL,
    created_by BIGINT,

    updated_at TIMESTAMP NOT NULL,
    updated_by BIGINT,

    CONSTRAINT fk_site_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id)
);