CREATE TABLE time_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    work_order_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,

    minutes INTEGER NOT NULL,
    note TEXT,

    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP NOT NULL,
    created_by BIGINT,

    updated_at TIMESTAMP NOT NULL,
    updated_by BIGINT,

    CONSTRAINT fk_timelog_workorder
        FOREIGN KEY(work_order_id)
        REFERENCES work_order(id),

    CONSTRAINT fk_timelog_user
        FOREIGN KEY(technician_id)
        REFERENCES users(id)
);